The identity function, a function that returns its argument

In [1]:
def identity(x):
    return x

In [2]:
identity(2)

2

In [ ]:
# In contrast, if you use a Python lambda construction, you get the fofo, , llowing:

In [3]:
lambda x: x

In [4]:
lambda x: x + 1

In [ ]:
#You can apply the function above to an argument by surrounding the function and its argument with parentheses:

In [5]:
(lambda x: x)(4)

4

In [6]:
(lambda x: x+1)(4)  #(lambda x: x + 1)(4) = lambda 4: 4 + 1 =5

5

In [7]:
(lambda x: x * x)(3)

9

In [8]:
add_one = lambda x: x + 1
add_one(3)

4

In [9]:
def add_one(x):
    return x + 1

In [ ]:
#These functions all take a single argument

In [10]:
## tile method for string:
str1 = 'geeKs foR geEks'
str2 = str1.title()

In [11]:
str2

'Geeks For Geeks'

In [12]:
full_name = lambda first, last: f'Nome-Cognome: {first.title()} {last.title()}'

In [13]:
full_name('guido', 'van rossum')

'Nome-Cognome: Guido Van Rossum'

In [14]:
# multiple argument
lambda x, y: x + y

In [15]:
(lambda x, y: x + y)(5, 6)

11

In [16]:
(lambda x, y, z: x + y + z)(1, 2, 3)

6

In [17]:
(lambda x, y, z=3: x + y + z)(1, 2)

6

In [18]:
(lambda *args: sum(args))(1,2,3,4,5)

15

In [19]:
(lambda x, y=0, z=0: x + y + z)(1, y=2, z=3)

6

In [20]:
(lambda x, y=0, z=0: x + y + z)(1,y=32,z=1)

34

In [21]:
(lambda x, y=0, z=0: x + y + z)(1,y=32,z=1,6)

SyntaxError: ignored

In [22]:
def cube(y): 
    return y*y*y; 
    
print(cube(5)) 

g = lambda x: x*x*x 
print(g(5))

125
125

map(f, list) → applies function f to all elements in list. Return a iterator of the result. (does not modify the original list)
In python 3, they return a iterator object that represent the list.

In [23]:
# Return double of n 
def addition(n): 
    return n + n 
  
# We double all numbers using map() 
numbers = (1, 2, 3, 4) 
result = map(addition, numbers) 
print(list(result))

[2, 4, 6, 8]

In [ ]:
numbers*2

(1, 2, 3, 4, 1, 2, 3, 4)

In [24]:
# Double all numbers using map and lambda 
  
numbers = (1, 2, 3, 4) 
result = map(lambda x: x + x, numbers) 
print(list(result))

[2, 4, 6, 8]

In [25]:
# Add two lists using map and lambda 
  
numbers1 = [1, 2, 3] 
numbers2 = [4, 5, 6] 
  
result = map(lambda x, y: x + y, numbers1, numbers2) 
print(list(result))

[5, 7, 9]

In [26]:
# List of strings 
lista = ['lune', 'marte'] 
  
# map() can listify the list of strings individually 
test = map(list, lista)
print(list(test))

[['l', 'u', 'n', 'e'], ['m', 'a', 'r', 't', 'e']]

In [27]:
lista1 = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61]*2
lista1

[5, 7, 22, 97, 54, 62, 77, 23, 73, 61, 5, 7, 22, 97, 54, 62, 77, 23, 73, 61]

In [28]:
sorted(lista1, reverse=True)

[97, 97, 77, 77, 73, 73, 62, 62, 61, 61, 54, 54, 23, 23, 22, 22, 7, 7, 5, 5]

In [31]:
## double list values
lista1 = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61] 
double_list = map(lambda x: x*2 , lista1)
print(list(double_list))

[10, 14, 44, 194, 108, 124, 154, 46, 146, 122]

In [32]:
# filter() with lambda() 
lista = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61] 
lista_filt = list(filter(lambda x: (x%2 != 0) , lista)) 
print(lista_filt)

[5, 7, 97, 77, 23, 73, 61]

In [33]:
from functools import reduce
lista2 = [5, 8, 10, 20, 50, 100] 
somma_lista = reduce((lambda x, y: x + y), lista2) 
print (somma_lista)

193

In [34]:
5+8+10+170

193

In [35]:
import pandas as pd

In [36]:
df=pd.DataFrame({
    'id':[1,2,3,4,5],
    'name':['Jeremy','Frank','Janet','Ryan','Mary'],
    'age':[20,25,15,10,30],
    'income':[4000,7000,200,0,10000]
})
df

   id    name  age  income
0   1  Jeremy   20    4000
1   2   Frank   25    7000
2   3   Janet   15     200
3   4    Ryan   10       0
4   5    Mary   30   10000

In [39]:
df['age_doppio']=df.apply(lambda x: x['age']*2,axis=1)
df

   id    name  age  income  age_doppio
0   1  Jeremy   17    4000          34
1   2   Frank   22    7000          44
2   3   Janet   12     200          24
3   4    Ryan    7       0          14
4   5    Mary   27   10000          54

In [40]:
df['age']=df['age'].apply(lambda x: x+3)
df

   id    name  age  income  age_doppio
0   1  Jeremy   20    4000          34
1   2   Frank   25    7000          44
2   3   Janet   15     200          24
3   4    Ryan   10       0          14
4   5    Mary   30   10000          54

In [42]:
list(filter(lambda x: x>18,df['age']))

[20, 25, 30]

In [43]:
df['income_perf20']=list(map(lambda x: int(x+x*0.2),df['income']))
df

   id    name  age  income  age_doppio  income_perf20
0   1  Jeremy   20    4000          34           4800
1   2   Frank   25    7000          44           8400
2   3   Janet   15     200          24            240
3   4    Ryan   10       0          14              0
4   5    Mary   30   10000          54          12000

In [44]:
df['category']=df['age'].apply(lambda x: 'Adult' if x>=18 else 'Child')
df

   id    name  age  income  age_doppio  income_perf20 category
0   1  Jeremy   20    4000          34           4800    Adult
1   2   Frank   25    7000          44           8400    Adult
2   3   Janet   15     200          24            240    Child
3   4    Ryan   10       0          14              0    Child
4   5    Mary   30   10000          54          12000    Adult